spring:
  application:
    name: SpringCloudSentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9000
  datasource:
    url: jdbc:mysql://192.168.34.79:3306/local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver